development:
  adapter: solid_cable
  database_url: <%= ENV.fetch("DATABASE_URL") { "postgres://localhost/casalink_development" } %>

test:
  adapter: test

production:
  adapter: solid_cable
  database_url: <%= ENV["DATABASE_URL"] %>
